### ISSUE TITLE
Adding custom theme

### ISSUE THREAD

**Issue by jmayermsi** [wheatstalk/cdk-ecs-keycloak#196]
Hello,
Thanks again for putting this together

Some questions, if you wanted to add some custom themes to the container how would the syntax look? Have multiple custom themes that I would like to include.  Also if you want to apply a custom domain name is that done with the setup scripts or is this handled after the script generates the instances

**Comment by misterjoshua** [comment]
> Some questions, if you wanted to add some custom themes to the container how would the syntax look? Have multiple custom themes that I would like to include.

To include your custom themes, you will need to bake them into a custom image. I have an example of how to create a similar image in one of my integration tests:

- https://github.com/wheatstalk/cdk-ecs-keycloak/blob/master/src/integ/integ-keycloak-cluster-custom-container-stack.ts
- https://github.com/wheatstalk/cdk-ecs-keycloak/tree/master/src/integ/custom-container

The key difference in your case would be to use your `Dockerfile` to copy your themes to `/opt/jboss/keycloak/themes/*`, where Keycloak knows to look.

> Also if you want to apply a custom domain name is that done with the setup scripts or is this handled after the script generates the instances

Your best bet here would be to bake your cli scripts into `/opt/jboss/startup-scripts/` via your `Dockerfile`.

Does this make sense?
